### ISSUE TITLE
HTTP resource type for the Icinga 2 ReST API

### ISSUE THREAD

**Issue by Al2Klimov** [Icinga/icingaweb2#3035]
* base URL `SCHEME://HOST[:PORT][/PREFIX]`
* basic authn credentials (optional)
* TLS cert + key (optional)
* remote TLS cert chain auto-discovery and confirming

## Subtasks

* [x] ResourceConfigForm: add subforms instead of their elements
* [x] Resource config forms: centralize name element
* [ ] #3016 (for TLS client identities and https://github.com/Icinga/icingaweb2/issues/3035#issuecomment-339961551)
* [ ] iplx/Http (for the actual usage of the resource)
* [x] #3022 (temp. L.F.S.)
* [x] actual HTTP(S) resource
* [ ] actually use the resource in the Icinga API cmd. transport
* [ ] ability to directly upload the TLS client identity (for the wizard context, probably by a subform which is to be done in #3016)
* [ ] #2790

**Comment by Al2Klimov** [comment]
blocked by #3016

**Comment by Al2Klimov** [comment]
blocked by #3042

**Comment by Al2Klimov** [comment]
blocked by #3044

**Comment by Al2Klimov** [comment]
blocked by #3046, not #3044

**Comment by Al2Klimov** [comment]
blocked by #3048

**Comment by Al2Klimov** [comment]
https://github.com/Icinga/icingaweb2/issues/2544#issuecomment-338918912

**Comment by Al2Klimov** [comment]
@nilmerg Should I apply https://github.com/Icinga/icingaweb2/pull/2866#pullrequestreview-72105503 here as well?

**Comment by Al2Klimov** [comment]
Notes for the future myself:
* "Not 'ReST API', but 'HTTP'" – @Thomas-Gelf
* Just no-CN-check, no "discovered CN"

**Comment by Thomas-Gelf** [comment]
@Al2Klimov: not 'HTTP' but 'Icinga 2 API Endpoint'

And I guess we agree on the fact the CN-part isn't satisfying...

**Comment by Al2Klimov** [comment]
@Thomas-Gelf

1. OK, to be clear you said 'HTTP', but then you corrected youself to 'Icinga 2 API Endpoint'. But I still like the idea that the Icinga 2 API cmd. endpoint is "just a" use case and other mods may benefit from this. (And I think @lippserd also does.)
2. The CN part would be extremely satisfying if either *someone* would not force everyone to use PHP cURL or *someone else* would create TLS certs with CNs matching the host names. I don't like both of this barriers, but during my professional education at NETWAYS I learned to make my life easier by saying my opinion, but executing commands w/o any scruple – no matter how great the damage may be. If you have desire and time to annoy @lippserd w/ that – go on and do your thing.

**Comment by Al2Klimov** [comment]
Notes for the future myself at work:

* investigate for a dirty hack for the CurlClient

**Comment by Thomas-Gelf** [comment]
?!

> OK, to be clear you said 'HTTP', but then you corrected youself to 'Icinga 2 API Endpoint'

We also said 'TCP' and 'TLS' and more, but then settled on 'Icinga 2 API Endpoint'. As far as I remember @lippserd agreed on this.

> [..] create TLS certs with CNs matching the host names

That's the default. If you recall the examples we explained today you'll realize that perfect certs alone will not help. Your rant does not address those problems. We all agreed that CURL isn't perfect for the given task, but also the available alternatives have their problems. I'm glad to hear that you experienced a professional education. Being professional sometimes means finding good compromises. The world isn't always perfect.

Your problem is that an Icinga Endpoint definition might carry a `host` property that might not match the `Endpoint name`. This could have various reasons, most of them derive from the not-so-perfect-world out there. Such reasons are DNS-less environments, distinct/split DNS, NAT and more. The Icinga cluster communication protocol has been implemented with such weird environments in mind. This is where the flexible Endpoint object definition has it's roots. The REST API sits on top of that Endpoint. You might not agree with this. You might have found a better solution at the time being. But now you have to deal with what we have. Big-mouthed rants are neither professional nor helpful. Being professional means evaluating the available options that could be realized at a reasonable cost. Being professional means to then come up with a viable solution.

So, while a hacky CURL-based solution would still be great, your other options might be:

* opt for another HTTP client implementation. Something you'd probably not be able to do without consent from @lippserd 
* specify that your *Icinga 2 API Endpoint* resource type is only available for systems with a resolvable DNS name matching their endpoint name. Might be an option, as you'll probably mostly just talk to Linux/Unix-based Icinga master systems. They are usually well configured.
* let above variant be the default and give users with suboptimal environments the possibility to opt out from a default secure configuration. The [vSphere module](https://github.com/Icinga/icingaweb2-module-vsphere) configuration should be a good example, as it does exactly this - based on CURL:

![vSphere Import Source configuration](https://raw.githubusercontent.com/Icinga/icingaweb2-module-vsphere/master/doc/screenshot/03_import-source/035_configure-connection.png)

In addition, it optionally allows to use a proxy, either based on SOCKS or (eventually authenticated) HTTP.

Have fun and keep up the good work!
Thomas.

**Comment by Al2Klimov** [comment]
I think I'll just rename it to HTTP... and if you are right about what @lippserd agreed with, he will instruct me to do like you told. (Just another rename isn't rocket science.) Btw if we don't have 'HTTP', but 'Icinga 2 API Endpoint', that's not a resource at all – it's just a cmd. transport like #2544.

"Have fun and keep up the good work!" – I'll give my best.

**Comment by Al2Klimov** [comment]
Btw. if you intentionally have no DNS, you can still edit `/etc/hosts` (if your great compliances aren't blocking this ;-) ).

**Comment by Al2Klimov** [comment]
@nilmerg As discussed (offline): the last commit.

**Comment by Al2Klimov** [comment]
@nilmerg 2nd try...

**Comment by Al2Klimov** [comment]
As discussed w/ @nilmerg (offline): Nothing has to comply about required/invalid form data on resource type change – so now we *have to* centralize the 'name' element.

**Comment by Al2Klimov** [comment]
Note: The last commit actually stores the root CA cert as PEM in the INI file which is *not* what we want. #3016

**Comment by Al2Klimov** [comment]
As discussed w/ @lippserd (offline):

* There is an (abstract) resource type 'HTTP'
* Modules may provide concrete resource types, maybe based on 'HTTP'
* The monitoring module provides a resource type 'Icinga 2 API'

CC @Thomas-Gelf

**Comment by Al2Klimov** [comment]
As discussed w/ @lippserd (offline):

No resources, neither "Icinga 2 API", nor "HTTP". As long as our "monitoring configuration model" (IDO DB resource + cmd. transport) stays as is (we'll have something new in the future), everything that requires the Icinga 2 API has to search for it in the cmd. transports.
