### ISSUE TITLE
Vagrant: Setup Icinga 2 API and configure command transport

### ISSUE THREAD

**Issue by dnsmichi** [Icinga/icingaweb2#3498]
The development environment doesn't use the Icinga 2 API as command transport, whereas we don't test that regularly then.

In addition to that I wanted to reproduce icinga/icinga2#6421 and had no API to use the debug console for further analysis.

## Tasks

- [ ] `icinga2 api setup`
- [ ] `object ApiUser "root" { password = "icinga"  }`
- [ ] commandtransports.ini -> new entry
- [ ] Decide whether to use this as a new default

**Comment by Al2Klimov** [comment]
* Not a thing anymore since v2.11: #4762
