### ISSUE TITLE
Adjust `ConfigForm` to write configurations to database

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingaweb2#4779]
# Preparations

1) Checkout #4778 and base off a new branch from it.
2) Apply the migration scripts for version 2.11 to the mysql and postgresql database.

# Goal

The class `ConfigForm` is the base class for many configuration forms. Most of it doesn't have to change to store their configs in database instead of INI files. Once the tasks are all finished, most child classes must not have changed. There may be some exceptions, if base implementations are overridden for example, but this should be not the case often.

# Tasks

* [x] Identify the config scope based on the file path that's assigned to the `Config` object
* [x] Adjust `ConfigForm::onRequest()` to load the values from database. It should ignore the options in the `Config` object
* [x] Introduce a new base element that's added to all forms, which holds the `hash` associated with the config scope. If there's no scope in the database yet, leave the hash element empty
* [x] Adjust `ConfigForm::writeConfig()` to write the configuration to database. Ensure to use a transaction for all statements
  * [x] Create the configuration scope if it doesn't exist yet. Calculcate the hash based on all option tuples `sha1(name=value, name=value, ...)`
  * [x] Don't try to patch already existing entries in the database. Run a `DELETE` and then multiple `INSERT` statements (I'll prepare ipl-sql so that it supports UPSERT which replaces this first approach)

**Comment by nilmerg** [comment]
Just saw [this](https://github.com/Icinga/icingaweb2/pull/4782/commits/0090301b51955e07be803d09d2c2e4282ca37688#diff-5f9e0c1b9698b0556a846140c5919c91a12c9afa3a424a154bc49aef54b7f043R60) change.

I see why you've added it, and I think it invalidates my assumption:

> Most of it doesn't have to change to store their configs in database instead of INI files.

The class `ConfigForm` has absolutely **no idea** which section of the INI configuration is being updated/added/deleted. Most of the time. The `GeneralConfigForm` and similar incarnations are an exception. The `ResourceConfigForm` is a rather bad example even, as it identifies the section by a URL parameter, **internally**...

So, I have to admit that I think it won't work ever, if we assume that the migration to database works out of the box for every concrete implementation of class `ConfigForm`. It starts with what scope to load **and display**. We could diff on write which section has changed, that's easy, but we cannot know which section to load, unless told.

And that's the only solution I see, we need to be told the section name. Explicitly. I've already hinted at a new method that implementors could use to migrate to. That could be the method `setConfigScope(string $name, string $type, string $module = 'default')`. Only if this is called, the db support is enabled. So you don't have to identify the scope based on the file path even. Anyone still calling `setIniConfig`, loads and writes INI config.
